### ISSUE TITLE
useRosTime in settings/client.xml doesn't work

### ISSUE THREAD

**Issue by worldpotato** [QuanergySystems/quanergy_client_ros#10]
# The problem:
The ros node doesn't use the ros time even if the value for useRosTime is set to true. The default value is true, see:

https://github.com/QuanergySystems/quanergy_client_ros/blob/bd7bcac41fafaba3b568a24b01be193e15c4c140/settings/client.xml#L6

# How it should work:
The ros node should use the ros time if it is set in the settings.

# possible solution
I think the option should be renamed to `use-ros-time` because it is read with as that name value. See:
https://github.com/QuanergySystems/quanergy_client_ros/blob/bd7bcac41fafaba3b568a24b01be193e15c4c140/src/client_node.cpp#L72

**Comment by rossctaylor** [comment]
Thanks for pointing this out. It looks like the problem is the parent node name for the setting. The code is expecting Settings.RosNode.useRosTime:
https://github.com/QuanergySystems/quanergy_client_ros/blob/bd7bcac41fafaba3b568a24b01be193e15c4c140/src/client_node.cpp#L333
While the default settings uses Settings.ClientRos.useRosTime:
https://github.com/QuanergySystems/quanergy_client_ros/blob/bd7bcac41fafaba3b568a24b01be193e15c4c140/settings/client.xml#L3

I will get this fixed soon. In the meantime, you can change ClientRos to RosNode in the settings file or use the command line option (--use-ros-time) to override.
